### ISSUE TITLE
cannot close embedded editor for LSP python code

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_embed_ed#15]
plugin 'HTML Tooltips'. opened definition of HTMLParser.
button [close] don't work at all!
![Screenshot from 2021-06-14 19-37-33](https://user-images.githubusercontent.com/4154978/121927793-2199d080-cd48-11eb-9dbf-03dd9a8501e2.png)

**Comment by Alexey-T** [comment]
console shows
```
Python 3.8.5
Init: cuda_hilite_occurrences
Init: cuda_lsp
Loaded session: "history session.json", 0ms, 0 file(s)
Startup: 170ms, plugins: 40ms (hilite_occurrences 26ms, lsp 22ms)
Init: cuda_addonman
Init: cuda_tab_icons
LSP: starting server - Python; root: None
Init: cudatext
Init: cuda_lsp.dlg
Init: cuda_embed_ed
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 509, in on_btn
    self.hide()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 509, in on_btn
    self.hide()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 509, in on_btn
    self.hide()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 509, in on_btn
    self.hide()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 511, in on_btn
    self.to_new_tab()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 531, in to_new_tab
    self.hide(animate=False)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 511, in on_btn
    self.to_new_tab()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 531, in to_new_tab
    self.hide(animate=False)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 511, in on_btn
    self.to_new_tab()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 531, in to_new_tab
    self.hide(animate=False)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 511, in on_btn
    self.to_new_tab()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 531, in to_new_tab
    self.hide(animate=False)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 188, in on_dlg_btn
    embed.on_btn(info)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 509, in on_btn
    self.hide()
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 573, in hide
    cancel = self.save_text(dlg=True)
  File "/home/user/.config/cudatext/py/cuda_embed_ed/embed_ed.py", line 560, in save_text
    with open(self.full_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
ERROR: Exception in CudaText for on_dlg_btn: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/html/parser.py'
```

**Comment by halfbrained** [comment]
Fixed. And now save button is disabled for read-only files
